version: "3"

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD

volumes:
  database:
    driver: local
